### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by linezero** [linezero/GitServer#1]
- [ ] Bootstarp

- [ ] Material Design http://materializecss.com/

- [x] Semantic UI http://www.semantic-ui.com

**Comment by wj-Mcat** [comment]
首先肯定是需要使项目能够支持换皮肤，semantic-ui可以作为第一个皮肤，后期我们可以引入更多的当前流行的皮肤。
ps：**bootstrap** 的话，我们还是找基于BS的框架嘛，而这些多的数都数不过来，2333

**Comment by RainingNight** [comment]
Angular Material [https://material.angular.io/](https://material.angular.io/)

**Comment by a764578566** [comment]
First feel ：Semantic UI

**Comment by linezero** [comment]
Semantic UI
